import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: {
    slug: string;
  };
};

export default async function PageLayout({ children, params }: LayoutProps) {
  console.log("here", params);

  const user = await fetch(
    "https://fortunate-viper-488.convex.site/get-clerk-user",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ clerkUserId: params.slug }),
    }
  );
  const userData = await user.json();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 shadow">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Book an event with {userData.name.replace("null", "")}
          </h1>
          <Link
            href={`/${params.slug}`}
            className="text-primary hover:text-primary/80 flex gap-2 items-center"
          >
            <ArrowLeft size={16} /> Back to Cal
          </Link>
        </div>
      </header>
      {children}
    </div>
  );
}
